[package]
name = "overlay"
version = "0.1.0"
edition = "2021"
authors = ["29th-Day"]

[lib]
name = "overlay"
crate-type = ["lib"]

# [profile]
# dev.panic = "abort"
# release.panic = "abort"


[dependencies]
wut = { path = "../wut", version = "*" }
notifications = { path = "../notifications", version = "*" }
